name: 💡 Add new Internship/Hackathon/Opensource Program
description: Adding new Internship to CZ
title: "[New Internship/Hackathon]: "
body:
  - type: checkboxes
    id: existing-issue
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for this feature.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a detailed description about the Internship/Hackathon.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Record
      options:
        - label: "I have read the Contributing Guidelines"
          required: true
        - label: "I'm a GSSOC'24 contributor"
          required: true
        - label: "I have starred the repository"
          required: true
